# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/45d23b3d-ec56-4f5e-9c93-ead4b61faf97";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/5603-15E2";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d2cd3070-a8ff-4807-8d97-7545bc4cf495"; }
    ];

  fileSystems."/home/zach/mounts/Drive2" = 
  	{ device = "/dev/disk/by-uuid/907a5290-0958-4ae9-856b-3fb77bcf48df";
      fsType = "ext4";
      options = ["nosuid" "nodev" "nofail" "x-gvfs-show"];
    };

  fileSystems."/home/zach/mounts/Backup" = 
    { device = "/dev/disk/by-uuid/a37339d0-5283-426b-915a-23bd442ff63f";
      fsType = "ext4";
      options = ["nosuid" "nodev" "nofail" "x-gvfs-show"];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
